---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: arc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/version: 0.27.6
    helm.sh/chart: actions-runner-controller-0.23.7
  name: arc-actions-runner-controller-metrics-service
  namespace: githubci
spec:
  clusterIP: 10.100.50.187
  clusterIPs:
  - 10.100.50.187
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics-port
    port: 8443
    protocol: TCP
    targetPort: metrics-port
  selector:
    app.kubernetes.io/instance: arc
    app.kubernetes.io/name: actions-runner-controller
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: arc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/version: 0.27.6
    helm.sh/chart: actions-runner-controller-0.23.7
  name: arc-actions-runner-controller-webhook
  namespace: githubci
spec:
  clusterIP: 10.100.113.209
  clusterIPs:
  - 10.100.113.209
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/instance: arc
    app.kubernetes.io/name: actions-runner-controller
  sessionAffinity: None
  type: ClusterIP
