---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: counter
  name: counter-headless
  namespace: live-migration
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: counter
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: counter
  name: counter-svc
  namespace: live-migration
spec:
  clusterIP: 10.100.39.6
  clusterIPs:
  - 10.100.39.6
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: counter
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: live-demo
  name: live-demo-svc
  namespace: live-migration
spec:
  clusterIP: 10.100.32.212
  clusterIPs:
  - 10.100.32.212
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: live-demo
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: migration-agent
  namespace: live-migration
spec:
  clusterIP: 10.100.47.166
  clusterIPs:
  - 10.100.47.166
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: migration-agent
  sessionAffinity: None
  type: ClusterIP
