---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hebrew-app
    tier: backend
  name: backend
  namespace: hebrew-app
spec:
  clusterIP: 10.100.153.215
  clusterIPs:
  - 10.100.153.215
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: hebrew-app
    tier: backend
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hebrew-app
    tier: frontend
  name: frontend
  namespace: hebrew-app
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.201.236
  clusterIPs:
  - 10.100.201.236
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31737
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hebrew-app
    tier: frontend
  sessionAffinity: None
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hebrew-app
    tier: db
  name: redis
  namespace: hebrew-app
spec:
  clusterIP: 10.100.63.135
  clusterIPs:
  - 10.100.63.135
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: hebrew-app
    tier: db
  sessionAffinity: None
  type: ClusterIP
