---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog-agent
  namespace: datadog

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog-cluster-agent
  namespace: datadog

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: datadog

