---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: datadog-cluster-agent
  name: datadog-cluster-agent
  namespace: datadog
spec:
  clusterIP: 10.100.6.185
  clusterIPs:
  - 10.100.6.185
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: agentport
    port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app: datadog-cluster-agent
  sessionAffinity: None
  type: ClusterIP
