---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: cloudprem
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cloudprem
    app.kubernetes.io/version: v0.1.22
    helm.sh/chart: cloudprem-0.2.2
  name: cloudprem-indexer
  namespace: cloudprem
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: indexer
      app.kubernetes.io/instance: cloudprem
      app.kubernetes.io/name: cloudprem
  serviceName: cloudprem-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/component: indexer
        app.kubernetes.io/instance: cloudprem
        app.kubernetes.io/name: cloudprem
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/capacity-type
                operator: In
                values:
                - on-demand
              - key: karpenter.k8s.aws/instance-family
                operator: In
                values:
                - t3
                - t3a
                - t4g
      containers:
      - args:
        - run
        - --service
        - indexer
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_COMPONENT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: KUBERNETES_LIMITS_CPU
          valueFrom:
            resourceFieldRef:
              containerName: cloudprem
              divisor: '0'
              resource: limits.cpu
        - name: KUBERNETES_LIMITS_MEMORY
          valueFrom:
            resourceFieldRef:
              containerName: cloudprem
              divisor: '0'
              resource: limits.memory
        - name: KUBERNETES_REQUESTS_CPU
          valueFrom:
            resourceFieldRef:
              containerName: cloudprem
              divisor: '0'
              resource: requests.cpu
        - name: KUBERNETES_REQUESTS_MEMORY
          valueFrom:
            resourceFieldRef:
              containerName: cloudprem
              divisor: '0'
              resource: requests.memory
        - name: QW_CONFIG
          value: /quickwit/node.yaml
        - name: QW_CLUSTER_ID
          value: cloudprem-cloudprem
        - name: QW_NODE_ID
          value: $(KUBERNETES_POD_NAME)
        - name: QW_PEER_SEEDS
          value: cloudprem-headless
        - name: QW_ADVERTISE_ADDRESS
          value: $(KUBERNETES_POD_IP)
        - name: QW_CLUSTER_ENDPOINT
          value: http://cloudprem-metastore.cloudprem.svc.cluster.local:7280
        - name: CP_DOGSTATSD_SERVER_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: CP_DOGSTATSD_SERVER_PORT
          value: '8125'
        - name: CP_ENABLE_REVERSE_CONNECTION
          value: 'true'
        - name: CP_MIN_SHARDS
          value: '12'
        - name: CP_RETENTION_PERIOD
          value: 30d
        - name: DD_SITE
          value: datadoghq.com
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              key: api-key
              name: datadog-secret
        - name: AWS_REGION
          value: us-east-1
        image: public.ecr.aws/datadog/cloudprem:v0.1.22
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/livez
            port: rest
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: cloudprem
        ports:
        - containerPort: 7280
          name: rest
          protocol: TCP
        - containerPort: 7281
          name: grpc
          protocol: TCP
        - containerPort: 7282
          name: discovery
          protocol: UDP
        - containerPort: 7283
          name: cloudprem
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/readyz
            port: rest
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: '1'
            memory: 4Gi
          requests:
            cpu: '1'
            memory: 4Gi
        securityContext:
          runAsNonRoot: true
          runAsUser: 1005
        startupProbe:
          failureThreshold: 12
          httpGet:
            path: /health/livez
            port: rest
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /quickwit/
          name: config
        - mountPath: /quickwit/qwdata
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1005
      serviceAccount: cloudprem
      serviceAccountName: cloudprem
      terminationGracePeriodSeconds: 300
      volumes:
      - configMap:
          defaultMode: 420
          name: cloudprem
        name: config
      - emptyDir: {}
        name: data
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      partition: 0
    type: RollingUpdate

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: cloudprem-postgres
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 18.3.0
    helm.sh/chart: postgresql-18.5.6
  name: cloudprem-postgres-postgresql
  namespace: cloudprem
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: cloudprem-postgres
      app.kubernetes.io/name: postgresql
  serviceName: cloudprem-postgres-postgresql-hl
  template:
    metadata:
      labels:
        app.kubernetes.io/component: primary
        app.kubernetes.io/instance: cloudprem-postgres
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/version: 18.3.0
        helm.sh/chart: postgresql-18.5.6
      name: cloudprem-postgres-postgresql
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/capacity-type
                operator: In
                values:
                - on-demand
              - key: karpenter.k8s.aws/instance-family
                operator: In
                values:
                - t3
                - t3a
                - t4g
      automountServiceAccountToken: false
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: 'false'
        - name: POSTGRESQL_PORT_NUMBER
          value: '5432'
        - name: POSTGRESQL_VOLUME_DIR
          value: /bitnami/postgresql
        - name: OPENSSL_FIPS
          value: 'yes'
        - name: PGDATA
          value: /bitnami/postgresql/data
        - name: POSTGRES_USER
          value: cloudprem
        - name: POSTGRES_PASSWORD_FILE
          value: /opt/bitnami/postgresql/secrets/password
        - name: POSTGRES_POSTGRES_PASSWORD_FILE
          value: /opt/bitnami/postgresql/secrets/postgres-password
        - name: POSTGRES_DATABASE
          value: cloudprem
        - name: POSTGRESQL_ENABLE_LDAP
          value: 'no'
        - name: POSTGRESQL_ENABLE_TLS
          value: 'no'
        - name: POSTGRESQL_LOG_HOSTNAME
          value: 'false'
        - name: POSTGRESQL_LOG_CONNECTIONS
          value: 'false'
        - name: POSTGRESQL_LOG_DISCONNECTIONS
          value: 'false'
        - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
          value: 'off'
        - name: POSTGRESQL_CLIENT_MIN_MESSAGES
          value: error
        - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
          value: pgaudit
        image: registry-1.docker.io/bitnami/postgresql:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "cloudprem" -d "dbname=cloudprem" -h 127.0.0.1 -p
              5432
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: postgresql
        ports:
        - containerPort: 5432
          name: tcp-postgresql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - -e
            - 'exec pg_isready -U "cloudprem" -d "dbname=cloudprem" -h 127.0.0.1 -p
              5432

              [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized
              ]

              '
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 150m
            ephemeral-storage: 2Gi
            memory: 192Mi
          requests:
            cpu: 100m
            ephemeral-storage: 50Mi
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
          seLinuxOptions: {}
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: empty-dir
          subPath: tmp-dir
        - mountPath: /opt/bitnami/postgresql/conf
          name: empty-dir
          subPath: app-conf-dir
        - mountPath: /opt/bitnami/postgresql/tmp
          name: empty-dir
          subPath: app-tmp-dir
        - mountPath: /opt/bitnami/postgresql/secrets/
          name: postgresql-password
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /bitnami/postgresql
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
      serviceAccount: cloudprem-postgres-postgresql
      serviceAccountName: cloudprem-postgres-postgresql
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: empty-dir
      - name: postgresql-password
        secret:
          defaultMode: 420
          secretName: cloudprem-postgres-postgresql
      - emptyDir:
          medium: Memory
        name: dshm
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: gp2
      volumeMode: Filesystem
    status:
      phase: Pending

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: cloudprem
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cloudprem
    app.kubernetes.io/version: v0.1.22
    helm.sh/chart: cloudprem-0.2.2
  name: cloudprem-searcher
  namespace: cloudprem
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: searcher
      app.kubernetes.io/instance: cloudprem
      app.kubernetes.io/name: cloudprem
  serviceName: cloudprem-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/component: searcher
        app.kubernetes.io/instance: cloudprem
        app.kubernetes.io/name: cloudprem
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/capacity-type
                operator: In
                values:
                - on-demand
              - key: karpenter.k8s.aws/instance-family
                operator: In
                values:
                - t3
                - t3a
                - t4g
      containers:
      - args:
        - run
        - --service
        - searcher
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_COMPONENT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: KUBERNETES_LIMITS_CPU
          valueFrom:
            resourceFieldRef:
              containerName: cloudprem
              divisor: '0'
              resource: limits.cpu
        - name: KUBERNETES_LIMITS_MEMORY
          valueFrom:
            resourceFieldRef:
              containerName: cloudprem
              divisor: '0'
              resource: limits.memory
        - name: KUBERNETES_REQUESTS_CPU
          valueFrom:
            resourceFieldRef:
              containerName: cloudprem
              divisor: '0'
              resource: requests.cpu
        - name: KUBERNETES_REQUESTS_MEMORY
          valueFrom:
            resourceFieldRef:
              containerName: cloudprem
              divisor: '0'
              resource: requests.memory
        - name: QW_CONFIG
          value: /quickwit/node.yaml
        - name: QW_CLUSTER_ID
          value: cloudprem-cloudprem
        - name: QW_NODE_ID
          value: $(KUBERNETES_POD_NAME)
        - name: QW_PEER_SEEDS
          value: cloudprem-headless
        - name: QW_ADVERTISE_ADDRESS
          value: $(KUBERNETES_POD_IP)
        - name: QW_CLUSTER_ENDPOINT
          value: http://cloudprem-metastore.cloudprem.svc.cluster.local:7280
        - name: CP_DOGSTATSD_SERVER_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: CP_DOGSTATSD_SERVER_PORT
          value: '8125'
        - name: CP_ENABLE_REVERSE_CONNECTION
          value: 'true'
        - name: CP_MIN_SHARDS
          value: '12'
        - name: CP_RETENTION_PERIOD
          value: 30d
        - name: DD_SITE
          value: datadoghq.com
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              key: api-key
              name: datadog-secret
        - name: AWS_REGION
          value: us-east-1
        image: public.ecr.aws/datadog/cloudprem:v0.1.22
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/livez
            port: rest
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: cloudprem
        ports:
        - containerPort: 7280
          name: rest
          protocol: TCP
        - containerPort: 7281
          name: grpc
          protocol: TCP
        - containerPort: 7282
          name: discovery
          protocol: UDP
        - containerPort: 7283
          name: cloudprem
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/readyz
            port: rest
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: '1'
            memory: 4Gi
          requests:
            cpu: '1'
            memory: 4Gi
        securityContext:
          runAsNonRoot: true
          runAsUser: 1005
        startupProbe:
          failureThreshold: 12
          httpGet:
            path: /health/livez
            port: rest
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /quickwit/node.yaml
          name: config
          subPath: node.yaml
        - mountPath: /quickwit/qwdata
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1005
      serviceAccount: cloudprem
      serviceAccountName: cloudprem
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: node.yaml
            path: node.yaml
          name: cloudprem
        name: config
      - emptyDir: {}
        name: data
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      partition: 0
    type: RollingUpdate
