---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: datadog
    app.kubernetes.io/managed-by: datadog-operator
    app.kubernetes.io/name: datadog-agent-deployment
    app.kubernetes.io/part-of: default-datadog
    app.kubernetes.io/version: ''
    operator.datadoghq.com/managed-by-store: 'true'
  name: datadog-agent
  namespace: default
  ownerReferences:
  - apiVersion: datadoghq.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: DatadogAgentInternal
    name: datadog
    uid: 7e3aeb43-9c84-4901-ae39-55b5fcf8322e

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: datadog
    app.kubernetes.io/managed-by: datadog-operator
    app.kubernetes.io/name: datadog-agent-deployment
    app.kubernetes.io/part-of: default-datadog
    app.kubernetes.io/version: ''
    operator.datadoghq.com/managed-by-store: 'true'
  name: datadog-cluster-agent
  namespace: default
  ownerReferences:
  - apiVersion: datadoghq.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: DatadogAgentInternal
    name: datadog
    uid: 7e3aeb43-9c84-4901-ae39-55b5fcf8322e

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: datadog-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: datadog-operator
    app.kubernetes.io/version: 1.22.0
    helm.sh/chart: datadog-operator-2.17.0
  name: datadog-operator
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default

