---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stock-postgres
  namespace: stock-app
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: stock-postgres
  serviceName: stock-postgres
  template:
    metadata:
      labels:
        app: stock-postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: stockdb
        - name: POSTGRES_USER
          value: trader
        - name: POSTGRES_PASSWORD
          value: StockSecret123!
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: postgres-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: gp2
      volumeMode: Filesystem
    status:
      phase: Pending
